# Generated by Django 4.2.16 on 2025-01-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для публикации.', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
